### ISSUE TITLE
Using Msigdb gene sets on regular gseapy

### ISSUE THREAD

**Issue by GabyBG** [krassowski/gsea-api#3]
Hello,

Thank you so much for sharing your code and make retrieving of datasets from MSigDB easier in Python! 

I am currently trying to run gseapy on some datasets. While I am able to run successfully enrichR, when I try to provide a GMT file downloaded from MSigDB it is not been recognized. That is how I came across your code, and has been very useful.

I was wondering if you tried using your dictionaries on regular gseapy. If you have, I would request a small vignette for that.

In my case I am trying something like:
res = gseapy.prerank(rnk=my_list_genes_ranked gene_sets=geneset_msigdb ,permutation_num=100)

Where geneset_msigdb = data obtained with your code (measured_subset)

And I get an error saying that the gene_sets could not be parsed.

Thank you for your work!

**Comment by krassowski** [comment]
I'm happy it's useful! I guess something like below should work:

```python
from gsea_api.gsea import GSEApy


gmt_path = GSEApy.solve_gene_sets(geneset_msigdb)
res = gseapy.prerank(rnk=my_list_genes_ranked, gene_sets=gmt_path, permutation_num=100)
```

**Comment by GabyBG** [comment]
It works, Thank you so much!
